#!/usr/bin/env bash
# This script is used to transfer a file to the server

if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file=$1
ip=$2
uname=$3
key=$4

scp -o StrictHostKeyChecking=no -i "$key" "$file" "$user@$ip:~/"
exit 0
