#!/usr/bin/env bash
# This bash script is used to install nginx on the server and set it up and running

sudo apt-get update -y
sudo apt-get install nginx -y

sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
