#!/usr/bin/env bash
# This script is used to setup and configure a load balancer

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*

sudo service haproxy start
echo "ENABLED=1" >> sudo tee /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

echo "global
    log /dev/log local0 notice
    maxconn 4096
    user haproxy
    group haproxy
defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5s
    timeout client 10s
    timeout server 10s
frontend myfrontend
    bind 0.0.0.0:80
    default_backend mybackend
backend mybackend
    balance roundrobin
    server 316681-web-01 54.160.68.240:80 check
    server 316681-web-02 34.232.71.122:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
