#!/usr/bin/env bash
# This script is used to setup and configure a load balancer

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install haproxy=2.8.\*

sudo service haproxy start

sudo cat << EOF | sudo tee /etc/haproxy/haproxy.cfg 
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    chroot /var/lib/
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000
frontend http-in
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back
backend http_back
    balance roundrobin
    server 316681-web-01 54.160.68.240:80 check
    server 316681-web-02 34.232.71.122:80 check
EOF
sudo service haproxy start
