#!/usr/bin/env bash
# this script dumps mysql data

if [ -z "$1" ]
then
	echo "add root password"
	exit 1
fi

PASSWORD="$1"

DATE="$(date +%d-%m-%Y)"

sudo mysqldump -u root -p"$PASSWORD" --all-databases | sudo tee backup.sql

tar -cvzf "$DATE.tar.gz" backup.sql
