#!/usr/bin/env bash
# this script is used to correct an nginx server to listen on port 80

if ! command -v nginx &> /dev/null
then
	echo "Nginx not installed"
	sudo apt-get update -y
	sudo apt-get install -y nginx
fi

if sudo systemctl is-active --quiet nginx
then
	echo "nginx is running"
else
	echo "nginx is not running"
	sudo service nginx start
fi

if sudo netstat -tuln | grep ":80" &> /dev/null
then
	echo "nginx is on port 80"
else
	echo "nginx is not on port 80, fixing it ..."
	sudo sed -i 's/listen .*/listen 80;/g' /etc/nginx/sites-available/default
	sudo service nginx restart
fi
