#!/usr/bin/env bash
# pid file and process

echo $$ > /var/run/myscript.pid
while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'Y U no love me?!'" SIGINT
	trap "echo 'I hate the kill command';rm -f /var/run/myscrip.pid; exit" SIGTERM
	trap "rm -f /var/run/myscript.pid; exit" SIGQUIT
done
