#!/usr/bin/env bash
# pid file and process

file="/var/run/myscript.pid"
echo $$ > /var/run/myscript.pid
while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm $file; exit" SIGQUIT SIGTERM
done
