#!/usr/bin/env bash
# pid file and process

echo $$ > /var/run/myscript.pid
while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'Y U no love me?!'" SIGINT
	trap "echo 'I hate the kill command';rm /var/run/myscrip.pid;exit" SIGTERM
	trap "rm /var/run/myscript.pid; exit" SIGQUIT
done
