#!/usr/bin/env bash
# this is the story of /etc/passwd

while IFS=':' read -r uname pass uid gid fname home shell
do
	echo "The user ${uname} is part of the ${gid} gang, lives in ${home} and rides ${shell}. ${uid}'s place is protected by the passcode ${pass}, more info about the user here: ${fname}"
done < /etc/passwd
