#!/usr/bin/env bash
# this script is used to change the localhost to 127.0.0.2
# and set 8.8.8.8 as facebook.com

cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
