#!/usr/bin/env bash
# This script configures nginx to be run by nginx user
sudo id -u nginx > /dev/null 2>&1 || sudo useradd -r -s /sbin/nologin nginx 
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sudo sed -i 's/user .*/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen .*/listen 8080;/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx
